# Generated by Django 3.0.8 on 2020-07-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200725_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
