# Generated by Django 3.0.8 on 2020-07-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_billingaddress_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='delivery_date',
        ),
    ]
