# Generated by Django 3.0.8 on 2020-07-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='measurement',
            field=models.CharField(blank=True, choices=[('OZ', 'ounce'), ('LB', 'pound'), ('FLOZ', 'fluid ounce')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
